/****************************
 * AUTO GENERATED BY LAMBDA *
 ****************************/
import {IndividualTickets, Passes } from './pricingTypes'

export const individualTickets: IndividualTickets = { 
	Feb: { 
		 Prebook:{
			 cost: 14,
			 studentCost: 12,
			 isAvailable: true,
			 priceId: 'price_1QQZObEWkmdeWsQPPK90RMv5',
			 studentPriceId: 'price_1QQZOtEWkmdeWsQPGgDY1I8x'
			 },
		},		
 }

export const initialSelectedOptions = {
	Feb: { 
		Prebook: false,
	}
 }

// Binary version = [Friday BiParty,Saturday Class Pass,Saturday Dinner,Saturday Party,Sunday Class Pass,Sunday Party]
export const passes: Passes = {
	'Febuary Pre Book': {
			cost: 0,
			studentCost: 0,
			isAvailable: true,
			saving: 2,
			studentSaving: 2,
			combination: ['Feb Prebook'],
			description: "Book in advance and save on the door",
			priceId: 'price_1QQneIEWkmdeWsQPJhsLrRof',
			studentPriceId: 'price_1QQnjjEWkmdeWsQPgurnBDwI'},
}

export const fullPassName = Object.keys(passes).at(1)
export const days = ['Prebook']
export const passTypes = Object.keys(individualTickets['Feb']).filter((item) => {
	console.log(Object.keys(individualTickets['Feb']))
	console.log(individualTickets['Feb'][item])
	console.log(individualTickets['Feb'][item].isAvailable)
		return individualTickets['Feb'][item].isAvailable
}) //['Party', 'Classes', 'Dinner']
